/* Generated By:JJTree: Do not edit this line. ArithmeticParserTreeConstants.java */

package zz.csg.api.constraints.parser;

public interface ArithmeticParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTREL = 1;
  public int JJTVOID = 2;
  public int JJTADD = 3;
  public int JJTSUB = 4;
  public int JJTMUL = 5;
  public int JJTDIV = 6;
  public int JJTMINUS = 7;
  public int JJTCONST = 8;
  public int JJTIDENTIFIER = 9;


  public String[] jjtNodeName = {
    "Start",
    "Rel",
    "void",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "Minus",
    "Const",
    "Identifier",
  };
}
