/* Generated By:JJTree: Do not edit this line. ASTMul.java */

package zz.csg.api.constraints.parser;

public class ASTMul extends SimpleNode {
  public ASTMul(int id) {
    super(id);
  }

  public ASTMul(ArithmeticParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ArithmeticParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
