/* Generated By:JJTree: Do not edit this line. ASTRel.java */

package zz.csg.api.constraints.parser;

import zz.csg.api.constraints.Constraint.*;

public class ASTRel extends SimpleNode {
	private Operator itsOp;
  public ASTRel(int id) {
    super(id);
  }

  public ASTRel(ArithmeticParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ArithmeticParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

public Operator getOp()
{
	return itsOp;
}

public void setOp(Operator aOp)
{
	itsOp = aOp;
}
  
  
}
