/* Generated By:JJTree: Do not edit this line. ASTStart.java */

package zz.csg.api.constraints.parser;

public class ASTStart extends SimpleNode {
  public ASTStart(int id) {
    super(id);
  }

  public ASTStart(ArithmeticParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ArithmeticParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
