/* Generated By:JJTree: Do not edit this line. ArithmeticParserVisitor.java */

package zz.csg.api.constraints.parser;

public interface ArithmeticParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTRel node, Object data);
  public Object visit(ASTAdd node, Object data);
  public Object visit(ASTSub node, Object data);
  public Object visit(ASTMul node, Object data);
  public Object visit(ASTDiv node, Object data);
  public Object visit(ASTMinus node, Object data);
  public Object visit(ASTConst node, Object data);
  public Object visit(ASTIdentifier node, Object data);
}
