/* Generated By:JJTree: Do not edit this line. ASTConst.java */

package zz.csg.api.constraints.parser;

public class ASTConst extends SimpleNode {
	private double itsValue;
	
  public ASTConst(int id) {
    super(id);
  }

  public ASTConst(ArithmeticParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ArithmeticParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

public double getValue()
{
	return itsValue;
}

public void setValue(double aValue)
{
	itsValue = aValue;
}
  
@Override
public String toString()
{
	return "Const: "+itsValue;
}
  
}
