/* Generated By:JJTree&JavaCC: Do not edit this line. ArithmeticParserConstants.java */
package zz.csg.api.constraints.parser;

public interface ArithmeticParserConstants {

  int EOF = 0;
  int DIGIT = 5;
  int LONG = 6;
  int DOUBLE = 7;
  int IDENTIFIER = 8;
  int LETTER = 9;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<DIGIT>",
    "<LONG>",
    "<DOUBLE>",
    "<IDENTIFIER>",
    "<LETTER>",
    "\"=\"",
    "\">=\"",
    "\"<=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
  };

}
