/* Generated By:JJTree: Do not edit this line. ASTMinus.java */

package zz.csg.api.constraints.parser;

public class ASTMinus extends SimpleNode {
  public ASTMinus(int id) {
    super(id);
  }

  public ASTMinus(ArithmeticParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ArithmeticParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
